-- Regenerates database/seed-reference-data.sql from a database the EF migrations have been
-- applied to, so the standalone seed script can never drift from the migrations' HasData:
--
--   sqlcmd -S "(localdb)\mssqllocaldb" -d <migrated db> -i database/generate-seed.sql -h -1 -y 8000 -f 65001 -o database/seed-reference-data.sql
--
-- The dynamic SQL is built from templates in which ~ stands for a single quote, which keeps the
-- quoting readable; it is swapped for NCHAR(39) just before execution.
SET NOCOUNT ON;

DECLARE @tables TABLE (Ordinal int, Name sysname);
INSERT INTO @tables VALUES (1, N'CauseOfLossCodes'), (2, N'ClaimStatusTransitions'), (3, N'Policies'), (4, N'PolicyCoverages');

PRINT N'-- Claims Module reference and simulated policy data (brief section 4.1).';
PRINT N'-- GENERATED by database/generate-seed.sql from the EF Core migrations'' seed data. Do not edit by hand.';
PRINT N'-- Idempotent: each row is inserted only if its Id is not already present. The EF migrations';
PRINT N'-- already apply this data; this script is for databases seeded outside EF.';
PRINT N'SET NOCOUNT ON;';
PRINT N'';

DECLARE @ordinal int = 1, @table sysname, @columns nvarchar(max), @values nvarchar(max), @sql nvarchar(max);
WHILE @ordinal <= 4
BEGIN
    SELECT @table = Name FROM @tables WHERE Ordinal = @ordinal;

    SELECT
        @columns = STRING_AGG(CAST(QUOTENAME(c.name) AS nvarchar(max)), N', ') WITHIN GROUP (ORDER BY c.column_id),
        @values = STRING_AGG(CAST(REPLACE(
            CASE
                WHEN TYPE_NAME(c.system_type_id) IN (N'bit', N'tinyint', N'smallint', N'int', N'bigint', N'decimal', N'numeric')
                    THEN N'CASE WHEN {c} IS NULL THEN N~NULL~ ELSE CONVERT(nvarchar(50), {c}) END'
                WHEN TYPE_NAME(c.system_type_id) = N'datetimeoffset'
                    THEN N'CASE WHEN {c} IS NULL THEN N~NULL~ ELSE N~~~~ + CONVERT(nvarchar(40), {c}, 127) + N~~~~ END'
                ELSE N'CASE WHEN {c} IS NULL THEN N~NULL~ ELSE N~N~~~ + REPLACE(CONVERT(nvarchar(max), {c}), N~~~~, N~~~~~~) + N~~~~ END'
            END, N'{c}', QUOTENAME(c.name)) AS nvarchar(max)), N' + N~, ~ + ') WITHIN GROUP (ORDER BY c.column_id)
    FROM sys.columns c
    WHERE c.object_id = OBJECT_ID(@table) AND c.is_computed = 0 AND TYPE_NAME(c.system_type_id) <> N'timestamp';

    SET @sql = REPLACE(REPLACE(REPLACE(REPLACE(
        N'SELECT N~IF NOT EXISTS (SELECT 1 FROM {t} WHERE [Id] = ~~~ + CONVERT(nvarchar(36), [Id]) + N~~~) INSERT INTO {t} ({cols}) VALUES (~ + {vals} + N~);~ FROM {t} ORDER BY [Id];',
        N'{vals}', @values), N'{cols}', @columns), N'{t}', QUOTENAME(@table)), N'~', NCHAR(39));

    PRINT N'-- ' + @table;
    EXEC sp_executesql @sql;
    PRINT N'';

    SET @ordinal += 1;
END
