// <auto-generated />
using System;
using System.Collections.Generic;
using ClaimsModule.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClaimsModule.Persistence.Migrations
{
    [DbContext(typeof(ClaimsDbContext))]
    partial class ClaimsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("ClaimNumberSequence", "dbo");

            modelBuilder.Entity("ClaimsModule.Domain.Entities.CauseOfLossCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganizationEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PerilCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserCreated")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserModified")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CauseOfLossCodes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000c1"),
                            Code = "COLL",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Collision",
                            IsActive = true,
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PerilCategory = "Auto",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000c2"),
                            Code = "COMP",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Comprehensive (non-collision)",
                            IsActive = true,
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PerilCategory = "Auto",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000c3"),
                            Code = "THEFT",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Theft",
                            IsActive = true,
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PerilCategory = "Auto",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000c4"),
                            Code = "FIRE",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Fire",
                            IsActive = true,
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PerilCategory = "Property",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000c5"),
                            Code = "WATER",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Water damage",
                            IsActive = true,
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PerilCategory = "Property",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000c6"),
                            Code = "WIND",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Windstorm/hail",
                            IsActive = true,
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PerilCategory = "Property",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000c7"),
                            Code = "SLIP",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Slip and fall",
                            IsActive = true,
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PerilCategory = "Liability",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000c8"),
                            Code = "PRODLIA",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Product liability",
                            IsActive = true,
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PerilCategory = "Liability",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000c9"),
                            Code = "OTHER",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Other / unclassified",
                            IsActive = true,
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PerilCategory = "Other",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000ca"),
                            Code = "LEGACY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Legacy / retired peril",
                            IsActive = false,
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PerilCategory = "Other",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000cb"),
                            Code = "B-COLL",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Collision (Org B)",
                            IsActive = true,
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PerilCategory = "Auto",
                            UserCreated = "seed"
                        });
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignedHandler")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSlaBreached")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganizationEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RequiresManagerOverride")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("SlaBreachedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserCreated")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserModified")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimNumber")
                        .IsUnique();

                    b.HasIndex("PolicyId");

                    b.ToTable("Claims", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganizationEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserCreated")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserModified")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("[IdempotencyKey] IS NOT NULL");

                    b.HasIndex("ClaimId", "CreatedAt");

                    b.ToTable("ClaimAuditLogs", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganizationEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SanitizedFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserCreated")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserModified")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimDocuments", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimParty", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("OrganizationEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PartyRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PartyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserCreated")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserModified")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimParties", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimReserveComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganizationEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserCreated")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserModified")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.ComplexProperty<Dictionary<string, object>>("CurrentAmount", "ClaimsModule.Domain.Entities.ClaimReserveComponent.CurrentAmount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("CurrentAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimReserveComponents", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimRiskObject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Identifier")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganizationEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserCreated")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserModified")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimRiskObjects", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimStatusTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganizationEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequiredPermission")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserCreated")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserModified")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("FromStatus", "ToStatus", "RequiredPermission")
                        .IsUnique();

                    b.ToTable("ClaimStatusTransitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000101"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Draft",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Handler",
                            ToStatus = "Open",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000102"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Draft",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Supervisor",
                            ToStatus = "Open",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000103"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Draft",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Manager",
                            ToStatus = "Open",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000107"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Open",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Handler",
                            ToStatus = "UnderInvestigation",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000108"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Open",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Supervisor",
                            ToStatus = "UnderInvestigation",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000109"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Open",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Manager",
                            ToStatus = "UnderInvestigation",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000110"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Open",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Handler",
                            ToStatus = "PendingPayment",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000111"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Open",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Supervisor",
                            ToStatus = "PendingPayment",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000112"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Open",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Manager",
                            ToStatus = "PendingPayment",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000113"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Open",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Handler",
                            ToStatus = "Closed",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000114"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Open",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Supervisor",
                            ToStatus = "Closed",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000115"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Open",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Manager",
                            ToStatus = "Closed",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000116"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "UnderInvestigation",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Handler",
                            ToStatus = "PendingPayment",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000117"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "UnderInvestigation",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Supervisor",
                            ToStatus = "PendingPayment",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000118"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "UnderInvestigation",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Manager",
                            ToStatus = "PendingPayment",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000119"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "UnderInvestigation",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Handler",
                            ToStatus = "Closed",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000120"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "UnderInvestigation",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Supervisor",
                            ToStatus = "Closed",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000121"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "UnderInvestigation",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Manager",
                            ToStatus = "Closed",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000122"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "PendingPayment",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Handler",
                            ToStatus = "Closed",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000123"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "PendingPayment",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Supervisor",
                            ToStatus = "Closed",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000124"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "PendingPayment",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Manager",
                            ToStatus = "Closed",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000125"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Draft",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Handler",
                            ToStatus = "Withdrawn",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000126"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Draft",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Supervisor",
                            ToStatus = "Withdrawn",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000127"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Draft",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Manager",
                            ToStatus = "Withdrawn",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000128"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Open",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Handler",
                            ToStatus = "Withdrawn",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000129"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Open",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Supervisor",
                            ToStatus = "Withdrawn",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000130"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Open",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Manager",
                            ToStatus = "Withdrawn",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000131"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "UnderInvestigation",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Handler",
                            ToStatus = "Withdrawn",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000132"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "UnderInvestigation",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Supervisor",
                            ToStatus = "Withdrawn",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000133"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "UnderInvestigation",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Manager",
                            ToStatus = "Withdrawn",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000135"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Closed",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Supervisor",
                            ToStatus = "Reopened",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000136"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Closed",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Manager",
                            ToStatus = "Reopened",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000137"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Reopened",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Handler",
                            ToStatus = "UnderInvestigation",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000138"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Reopened",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Supervisor",
                            ToStatus = "UnderInvestigation",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000139"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Reopened",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Manager",
                            ToStatus = "UnderInvestigation",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000140"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Reopened",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Handler",
                            ToStatus = "PendingPayment",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000141"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Reopened",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Supervisor",
                            ToStatus = "PendingPayment",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000142"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Reopened",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Manager",
                            ToStatus = "PendingPayment",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000143"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Reopened",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Handler",
                            ToStatus = "Closed",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000144"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Reopened",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Supervisor",
                            ToStatus = "Closed",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000145"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Reopened",
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequiredPermission = "Manager",
                            ToStatus = "Closed",
                            UserCreated = "seed"
                        });
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.LossEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CauseOfLossCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("LossDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OrganizationEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserCreated")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserModified")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CauseOfLossCodeId");

                    b.HasIndex("ClaimId")
                        .IsUnique();

                    b.ToTable("LossEvents", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("EffectiveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpirationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganizationEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserCreated")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserModified")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("PolicyNumber")
                        .IsUnique();

                    b.ToTable("Policies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000a1"),
                            ClientName = "Acme Logistics LLC",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EffectiveDate = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExpirationDate = new DateTimeOffset(new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PolicyNumber = "POL-2026-000101",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000a2"),
                            ClientName = "Harborview Property Group",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EffectiveDate = new DateTimeOffset(new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExpirationDate = new DateTimeOffset(new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PolicyNumber = "POL-2025-000202",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000a3"),
                            ClientName = "Meridian Retail Partners",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EffectiveDate = new DateTimeOffset(new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExpirationDate = new DateTimeOffset(new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PolicyNumber = "POL-2024-000303",
                            UserCreated = "seed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000a4"),
                            ClientName = "Short-Term Events Co",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EffectiveDate = new DateTimeOffset(new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExpirationDate = new DateTimeOffset(new DateTime(2026, 9, 7, 23, 59, 59, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            OrganizationEntityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PolicyNumber = "POL-2026-000404",
                            UserCreated = "seed"
                        });
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.PolicyCoverage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverageType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganizationEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserCreated")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserModified")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.ComplexProperty<Dictionary<string, object>>("Deductible", "ClaimsModule.Domain.Entities.PolicyCoverage.Deductible#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("DeductibleAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("DeductibleCurrency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Limit", "ClaimsModule.Domain.Entities.PolicyCoverage.Limit#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("LimitAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("LimitCurrency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("PolicyId");

                    b.ToTable("PolicyCoverages", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ReserveHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ChangeSequence")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DecidedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganizationEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PostingJobId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RequiredTier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ReserveComponentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserCreated")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserModified")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.ComplexProperty<Dictionary<string, object>>("Amount", "ClaimsModule.Domain.Entities.ReserveHistory.Amount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Currency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("NewAmount", "ClaimsModule.Domain.Entities.ReserveHistory.NewAmount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("NewAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("NewCurrency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PreviousAmount", "ClaimsModule.Domain.Entities.ReserveHistory.PreviousAmount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("PreviousAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("PreviousCurrency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ReserveComponentId", "ChangeSequence")
                        .IsUnique();

                    b.ToTable("ReserveHistories", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.Claim", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Entities.Policy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimDocument", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Entities.Claim", null)
                        .WithMany("Documents")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimParty", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Entities.Claim", null)
                        .WithMany("Parties")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimReserveComponent", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Entities.Claim", null)
                        .WithMany("ReserveComponents")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimRiskObject", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Entities.Claim", null)
                        .WithMany("RiskObjects")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.LossEvent", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Entities.CauseOfLossCode", "CauseOfLossCode")
                        .WithMany()
                        .HasForeignKey("CauseOfLossCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClaimsModule.Domain.Entities.Claim", null)
                        .WithOne("LossEvent")
                        .HasForeignKey("ClaimsModule.Domain.Entities.LossEvent", "ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CauseOfLossCode");
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.PolicyCoverage", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Entities.Policy", "Policy")
                        .WithMany("Coverages")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ReserveHistory", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Entities.ClaimReserveComponent", null)
                        .WithMany("History")
                        .HasForeignKey("ReserveComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.Claim", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("LossEvent")
                        .IsRequired();

                    b.Navigation("Parties");

                    b.Navigation("ReserveComponents");

                    b.Navigation("RiskObjects");
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.ClaimReserveComponent", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("ClaimsModule.Domain.Entities.Policy", b =>
                {
                    b.Navigation("Coverages");
                });
#pragma warning restore 612, 618
        }
    }
}
